[package]
name = "chain-vote"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent.hanquez@iohk.io>"]
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
chain-crypto = { path = "../chain-crypto", features = ["ristretto255"]}
rand = "0.8"
rand_core = "0.6"
rayon = "1.5"
thiserror = "1.0"
cryptoxide = "0.3"

[dev-dependencies]
rand_chacha = "0.3"
smoke = "^0.2.1"

criterion = "0.3"

[[bench]]
harness = false
name = "shvzk"

[[bench]]
harness = false
name = "curve"
