[package]
name = "imhamt"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent.hanquez@iohk.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "1.0"

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
criterion = "0.3.0"

[target.'cfg(unix)'.dev-dependencies]
jemalloc-ctl = "0.3"
jemallocator = "*"

[[example]]
name = "memdump"
path = "examples/memdump/main.rs"

[[bench]]
harness = false
name = "imhamt"
